#cloud-config
repo_update: true
repo_upgrade: all

# Required packages
packages:
  - java
  - wget

# Commands to run
runcmd:
  - su -l ec2-user -c "wget -qq https://github.com/redis-developer/riot/releases/download/v2.14.0/riot-redis-2.14.0.zip"
  - su -l ec2-user -c "unzip -q riot-redis-2.14.0.zip"
  - ln -s ~ec2-user/riot-redis-2.14.0/bin/riot-redis /usr/local/bin
  

